### ISSUE TITLE
Importing icg opens an empty project

### ISSUE THREAD

**Issue by ericdand** [drebain/icg#2]
<img width="472" alt="screen shot 2017-06-04 at 8 34 25 pm" src="https://cloud.githubusercontent.com/assets/2456006/26769638/5e405dda-4965-11e7-97ba-574a9d1153de.png">

When I follow the instructions on the Wiki, this is all I get. `git status` tells me I'm 100% up to date. What gives?

**Comment by ericdand** [comment]
All the files are actually there; I just can't get Qt Creator to see them.

Any tips on doing this just from the command line using cmake? That would probably suit me better anyhow.

**Comment by drebain** [comment]
I have seen this in cases where the CMake configuration does not complete correctly, or the kit that is selected is missing a compiler or CMake executable. Check the 'General Messages' tab, and make sure the output after opening the project contains 'Configuring done' and 'Generating done'. If it does not, see what error messages are printed for more information on what the problem is.

Otherwise, check that the kit you have selected in the projects tab has its compiler and CMake tool set.

To build from the command line, you need to make a build folder and invoke CMake in it. For example:

    cd <path-to-icg-repository>
    mkdir build
    cd build
    cmake ..
    make

Keep in mind that if you use the command line method you will need to re-run CMake any time you add/remove/rename files so that the makefile is kept up-to-date.

Also, the OpenGL-based subprojects like `assignment2` are configured to place their executables in the corresponding source folders, and need to be run with those folders as the working directory so that they can find the shader and texture files to load at runtime.

**Comment by ericdand** [comment]
Thanks, Daniel! Turns out the kit didn't have CMake nor a C compiler set up. Now I remember us doing that in labs.

Could you please add instructions for doing this to the "Development Environment Setup" wiki page? Then I think it will be fine to close this issue.

Edit: also, mentioning that you need to clone the git repo with `--recursive` is probably a good thing to note; I was also missing OpenGP.

**Comment by drebain** [comment]
I have updated the wiki page. Please let me know if there is anything else you think would be helpful to have there.
